### Create New User
POST http://localhost:5000/api/user
content-type: application/json

{
    "firstName": "Jake",
    "lastName": "Avery",
    "email": "javery@codingdojo.cl",
    "password": "test1234"
}

### Login
POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "javery@codingdojo.cl",
    "password": "test1234"
}

### Logout
POST http://localhost:5000/api/logout

### Create New Author
POST http://localhost:5000/api/author
Content-Type: application/json
# cookie: usertoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGEzMWU5NzE0YTdkODQzYzQ3OGYzNDYiLCJpYXQiOjE2MjE0NzM5NjV9.041Q751GVpaixlpg1XAG5r487DI09EXtilC3C8Ye1Dg; 

{
    "name": "JK Rowling"
}

### Create New Author Without Name
POST http://localhost:5000/api/author
content-type: application/json

{
   
}

### Get Authors 
GET http://localhost:5000/api/author
